### ISSUE TITLE
weights file

### ISSUE THREAD

**Issue by autogyro** [gittigxuy/yolo-v3-shirt-color-recognize#1]
Dear Xuy
I am very interesting at your works, May I have your trained weights model?
 many thanks!
Ed

**Comment by gittigxuy** [comment]
sorry,the result is not good,so,this repo I do not finish,for more detail,please refer to https://github.com/SpikeKing/keras-yolo3-detection.

**Comment by autogyro** [comment]
Cheers，GOOD LUCK TO YOU.
